services:
  - type: web
    name: municipalidad-carupano-api
    runtime: python
    buildCommand: pip install -r requirements.txt && python init_data.py
    startCommand: gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
